spring.application.name=OnlineShopping

spring.datasource.url=jdbc:postgresql://localhost:5432/onlineshopping
spring.datasource.username=postgres
spring.datasource.password=5142189
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view = false
spring.jpa.show-sql=true
